### ISSUE TITLE
clicking snooze....

### ISSUE THREAD

**Issue by justjim1220** [JanLoebel/MMM-TouchAlarm#1]
clicking snooze doesn't stop alarm...

**Comment by JanLoebel** [comment]
sadly true, sorry for that! I will fix it as soon as possible.

**Comment by JanLoebel** [comment]
Fixed:
https://github.com/JanLoebel/MMM-TouchAlarm/commit/2e38d9eb3550f892d7cc410a76534bf6dc28c680
