### ISSUE TITLE
Sizing of Alarm

### ISSUE THREAD

**Issue by chengy77** [JanLoebel/MMM-TouchAlarm#3]
I've tried using custom.css to adjust the alarm size. No luck. Any help pointing me in the right direction would be very much appreciated.

**Comment by JanLoebel** [comment]
Hi,

what do you mean by "Alarm"? Do you mean the clock itself? You can just use the transform-scale operator from css to scale the element like so:

```
.mmm-touchalarm {
  transform: scale(2);
}
```
